name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.0'
    - name: Install dependencies
      working-directory: sdk/test
      run: dotnet restore
    - name: Build
      working-directory: sdk/test
      run: dotnet build --configuration Release --no-restore
    - name: Test with the dotnet CLI
      working-directory: sdk/test
      run: dotnet test --no-restore --verbosity normal
