name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install version
      run: dotnet tool install --global dotnet-ef --version 3.1.0
    - name: Add package
      run: dotnet add package Microsoft.EntityFrameworkCore.Design
    - name: Install dependencies
      working-directory: sdk/test
      run: dotnet restore
    - name: Build
      working-directory: sdk/test
      run: dotnet build --configuration Release --no-restore
    - name: Test with the dotnet CLI
      working-directory: sdk/test
      run: dotnet test --no-restore --verbosity normal
